# Ansible task
- name: Update packages 
  dnf: 
    name: "*"
    state: latest

- name: Curl on repo to allow neofetch installation 
  command: curl -o /etc/yum.repos.d/konimex-neofetch-epel-7.repo https://copr.fedorainfracloud.org/coprs/konimex/neofetch/repo/epel-7/konimex-neofetch-epel-7.repo

- name: Enabling epel-release
  dnf: 
    name: "epel-release"
    state: latest

- name: Install essential packages 
  package: 
    name: "{{ packages }}"
    state: latest 

- name: Disable SSH password auth
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for "{{ username }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s" # revert changes in sudoers in case sudo fails

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed 
